aa: null
batch_size: 64
color_jitter: 0.06
decay_by_epoch: false
decay_epochs: 3.0
decay_rate: 0.963
drop: 0.0
epochs: 450
log_interval: 50
lr: 0.064
min_lr: 1.0e-05
model_ema: true
model_ema_decay: 0.9998
momentum: 0.9
opt: rmsproptf
opt_betas: null
opt_eps: 0.001
remode: const
reprob: 0.0
sched: step
seed: 42
warmup_epochs: 5
warmup_lr: 1.0e-06
weight_decay: 1.0e-05
workers: 4
