aa: null
batch_size: 32
color_jitter: 0.0
decay_by_epoch: True
decay_epochs: 1
decay_rate: 0.98
drop: 0.0
epochs: 300
log_interval: 50
lr: 0.045
min_lr: 1.0e-05
model_ema: false
model_ema_decay: 0.9998
momentum: 0.9
smoothing: 0.0
opt: sgd
opt_betas: null
opt_eps: 1.0e-08
remode: const
reprob: 0.0
sched: step
seed: 42
warmup_epochs: 0
warmup_lr: 0.2
weight_decay: 4.0e-5
workers: 4
