# 22/20 = 1.1
backbone:
    # name: [n, stride, in_channels, out_channels, expand_ratio, op]
    conv_stem: [1, 2, 3, 35, 1, 'conv3x3']
    stage_0: [1, 1, 35, 18, 1, 'ir_3x3']
    stage1: [2, 2, 18, 26, 6, 'ir_3x3']
    stage2: [3, 2, 26, 35, 6, 'ir_3x3']
    stage3: [4, 2, 35, 70, 6, 'ir_3x3']
    stage4: [3, 1, 70, 106, 6, 'ir_3x3']
    stage5: [3, 2, 106, 176, 6, 'ir_3x3']
    stage6: [1, 1, 176, 352, 6, 'ir_3x3']
    conv_out: [1, 1, 352, 1408, 1, 'conv1x1']
    gavg_pool: [1, 1408, 1408, 1, 'gavgp']
head:
    linear1:
        dim_in: 1408
        dim_out: 1000

