backbone:
    # name: [n, stride, in_channels, out_channels, expand_ratio, op]
    conv_stem: [1, 2, 3, 48, 1, 'conv3x3']
    stage_0: [1, 1, 48, 24, 1, 'ir_3x3']
    stage1: [2, 2, 24, 36, 6, 'ir_3x3']
    stage2: [3, 2, 36, 48, 6, 'ir_3x3']
    stage3: [4, 2, 48, 144, 6, 'ir_3x3']
    stage4: [3, 1, 144, 144, 6, 'ir_3x3']
    stage5: [3, 2, 144, 240, 6, 'ir_3x3']
    stage6: [1, 1, 240, 480, 6, 'ir_3x3']
    conv_out: [1, 1, 480, 1920, 1, 'conv1x1']
    gavg_pool: [1, 1920, 1920, 1, 'gavgp']
head:
    linear1:
        dim_in: 1920
        dim_out: 1000

