backbone:
    # name: [n, stride, in_channels, out_channels, expand_ratio, op]
    conv_stem: [1, 2, 3, 128, 1, 'conv3x3']
    stage_0: [2, 1, 128, 128, 6, 'ir_3x3']
    stage1: [1, 2, 128, 256, 6, 'ir_3x3']
    stage2: [1, 1, 256, 256, 6, 'ir_3x3']
    conv_out: [1, 1, 256, 1024, 1, 'conv1x1']
    gavg_pool: [1, 1024, 1024, 1, 'gavgp']
head:
    linear1:
        dim_in: 1024
        dim_out: 10

