# 25/20 = 1.25 X
backbone:
    # name: [n, stride, in_channels, out_channels, expand_ratio, op]
    conv_stem: [1, 2, 3, 43, 1, 'conv3x3']
    stage_0: [1, 1, 43, 14, 1, 'ir_3x3']
    stage1: [2, 2, 14, 32, 6, 'ir_3x3']
    stage2: [3, 2, 32, 43, 6, 'ir_3x3']
    stage3: [4, 2, 43, 86, 6, 'ir_3x3']
    stage4: [3, 1, 86, 130, 6, 'ir_3x3']
    stage5: [3, 2, 130, 216, 6, 'ir_3x3']
    stage6: [1, 1, 216, 432, 6, 'ir_3x3']
    conv_out: [1, 1, 432, 1728, 1, 'conv1x1']
    gavg_pool: [1, 1728, 1728, 1, 'gavgp']
head:
    linear1:
        dim_in: 1728
        dim_out: 1000

