backbone:
    # name: [n, stride, in_channels, out_channels, expand_ratio, op]
    conv_stem: [1, 2, 3, 67, 1, 'conv3x3']
    stage_0: [1, 1, 67, 34, 1, 'ir_3x3']
    stage1: [2, 2, 34, 50, 6, 'ir_3x3']
    stage2: [3, 2, 50, 67, 6, 'ir_3x3']
    stage3: [4, 2, 67, 202, 6, 'ir_3x3']
    stage4: [3, 1, 202, 202, 6, 'ir_3x3']
    stage5: [3, 2, 202, 336, 6, 'ir_3x3']
    stage6: [1, 1, 336, 672, 6, 'ir_3x3']
    conv_out: [1, 1, 672, 2688, 1, 'conv1x1']
    gavg_pool: [1, 2688, 2688, 1, 'gavgp']
head:
    linear1:
        dim_in: 2688
        dim_out: 1000

