retrain:
    flag: True
    # FLOPs: 333,598,784 FLOPs
    model:
      channels: [23, 23, 16, 10, 10, 24, 30, 30, 24, 12, 12, 32, 151, 151, 32, 157, 157, 32, 10, 10, 64, 315, 315, 64, 367, 367, 64, 353, 353, 64, 283, 283, 96, 487, 487, 96, 488, 488, 96, 156, 156, 160, 370, 370, 160, 71, 71, 160, 9, 9, 149, 1280] 
      backbone:
        # [n, stride, c_in, c_out, [expand_ratio], channel_search, [op]]
        conv_stem: [1, 2, 3, 32, [], False, ['conv3x3']]
        stage_0: [1, 1, 32, 16, [1], False, ['ir_3x3']]
        stage1: [2, 2, 16, 24, [6], False, ['ir_3x3']]
        stage2: [3, 2, 24, 32, [6], False, ['ir_3x3']]
        stage3: [4, 2, 32, 64, [6], False, ['ir_3x3']]
        stage4: [3, 1, 64, 96, [6], False, ['ir_3x3']]
        stage5: [3, 2, 96, 160, [6], False, ['ir_3x3']]
        stage6: [1, 1, 160, 320, [6], False, ['ir_3x3']]
        conv_out: [1, 1, 320, 1280, [], False, ['conv2d']]
        final_pooling: True
      head:
        linear1:
          dim_in: 1280
          dim_out: 1000
      loss_type: 's-softmax'

    strategy:
        max_iter: 752000
        optimizer:
            type: 'SGD'
            lr: 0.1  # in proxyless: 0.0125 per gpu
            weight_decay: 0.00005
            momentum: 0.9
            nesterov: True
        resume: False
        lr_scheduler:
            #base_lr: 0.12
            lr_steps: [50080, 100160, 125200]
            lr_mults: [0.1, 0.1, 0.1]
            warmup_steps: 12515  # warmup epochs: 5 steps=5*2503=12515
            warmup_strategy: 'gradual'
            warmup_lr: 0.2
            decay_stg: 'cosine'
            # final lr in cosine strategy
            alpha: 0.00001
            # how many iterations it takes to decay lr to 'alpha'
            decay_step: 730000

        task_type: 'imagenet'
        snapshot_freq: 1000
        print_freq: 20
        save_path: '../generalNAS_exp/imagenet_mbnetv2_rmean_new8'

    data:
        workers: 8  # dataloader worker num
        task_type: 'imagenet'
        data_type: 'ssst'
        scatter_mode: False
        final_height: 224
        final_width: 224
        final_channel: 3
        augmentation:
            rand_resize:
                output_size: 224
                scale: [0.08, 1.0]
                ratio: [0.75, 1.3333333333]
            affine:
                mirror:
                    mirror_prob: 0.5
            # resize
            resize:
                output_size: [224, 224]
            # normalize
            normalize:
                normalize_type: 'mean_std'
                mean: [123.675, 116.28, 103.53]
                std: [58.395, 57.120, 57.375]
        imagenet:
            type: 'classification'
            task: 'imagenet'
            json_path: '/mnt/lustre/suxiu/dataset/imagenet/imagenet.json'
            prefix: '/mnt/lustre/share/images/train'
            batch_size: 64 # for single gpu

test:
    flag: True
    model:
      channels: [23, 23, 16, 10, 10, 24, 30, 30, 24, 12, 12, 32, 151, 151, 32, 157, 157, 32, 10, 10, 64, 315, 315, 64, 367, 367, 64, 353, 353, 64, 283, 283, 96, 487, 487, 96, 488, 488, 96, 156, 156, 160, 370, 370, 160, 71, 71, 160, 9, 9, 149, 1280] 
      backbone:
        conv_stem: [1, 2, 3, 32, [], False, ['conv3x3']]
        stage_0: [1, 1, 32, 16, [1], False, ['ir_3x3']]
        stage1: [2, 2, 16, 24, [6], False, ['ir_3x3']]
        stage2: [3, 2, 24, 32, [6], False, ['ir_3x3']]
        stage3: [4, 2, 32, 64, [6], False, ['ir_3x3']]
        stage4: [3, 1, 64, 96, [6], False, ['ir_3x3']]
        stage5: [3, 2, 96, 160, [6], False, ['ir_3x3']]
        stage6: [1, 1, 160, 320, [6], False, ['ir_3x3']]
        conv_out: [1, 1, 320, 1280, [], False, ['conv2d']] 
        final_pooling: True
      head:
        linear1:
          dim_in: 1280
          dim_out: 1000
      loss_type: 's-softmax'

    strategy:
        task_type: 'imagenet-test'
        snapshot_freq: 2000
        print_freq: 20
        save_path: '../generalNAS_exp/imagenet_mbnetv2_rmean_new8/checkpoint'
        load_iter: 750000
        start: 742000
        end: 752000
        strip: 200

    data:
        workers: 8  # dataloader worker num
        task_type: 'imagenet-test'
        data_type: 'ssst'
        scatter_mode: False
        final_height: 224
        final_width: 224
        final_channel: 3
        augmentation:
            resize:
                output_size: 256
            center_crop:
                output_size: 224
            normalize:
                normalize_type: 'mean_std'
                mean: [123.675, 116.28, 103.53]
                std: [58.395, 57.120, 57.375]
        imagenet:
            type: 'classification'
            task: 'imagenet'
            json_path: '/mnt/lustre/suxiu/dataset/imagenet/imagenet_val.json'
            prefix: '/mnt/lustre/share/images/val'
            batch_size: 32 # for single gpu

