workers: 4
epochs: 600
start_epoch: 0
batch_size: 96
lr_scheduler:
    type: 'cosine'
    lr: 0.2
    warmup_epochs: 30
momentum: 0.9
weight_decay: 3.e-4
nesterov: False
grad_clip: 5
print_freq: 20
resume:
save: './workdir/darts/cifar10-eval-paper-gpu8'
evaluate: False

data:
    type: 'cifar10'
    root: './data/cifar10'
    cutout: True
    cutout_length: 16

model:
    type: 'DARTSEvalModel'
    drop_path_prob: 0.2
    auxiliary_weight: 0.4
    backbone:
        type: 'DARTSEvalNetworkCIFAR'
        C: 36
        num_classes: 10
        layers: 20
        auxiliary: True
        genotype: "Genotype(normal=[('sep_conv_3x3', 0), ('sep_conv_3x3', 1), ('sep_conv_3x3', 0), ('sep_conv_3x3', 1), ('sep_conv_3x3', 1), ('skip_connect', 0), ('skip_connect', 0), ('dil_conv_3x3', 2)], normal_concat=[2, 3, 4, 5], reduce=[('max_pool_3x3', 0), ('max_pool_3x3', 1), ('skip_connect', 2), ('max_pool_3x3', 1), ('max_pool_3x3', 0), ('skip_connect', 2), ('skip_connect', 2), ('max_pool_3x3', 1)], reduce_concat=[2, 3, 4, 5])"
    loss:
        type: 'CrossEntropyLoss'

trainer:
    type: 'DARTS'
    stage: ['evaluate']
