workers: 4
epochs: 50
start_epoch: 0
batch_size: 128
lr_scheduler:
    type: 'cosine'
    lr: 0.5
    warmup_epochs: 5
momentum: 0.9
weight_decay: 3.e-5
nesterov: False
grad_clip: 5
print_freq: 20
resume: 
save: './workdir/pcdarts/imagenet-train-search'
evaluate: False
#seed: 0
#tensorboard:                                                              
#    root: '/mnt/lustre/zhuyuanhao/runs/pcdarts-imagenet-train-search'

data:
    type: 'imagenet'
    traindir: '/mnt/lustre/share/images/train/'
    trainlabel: './data/imagenet/meta_pcdarts/train.txt'
    valdir: '/mnt/lustre/share/images/train/'
    vallabel: './data/imagenet/meta_pcdarts/val.txt'

model:
    type: 'DARTSSearchModel'
    backbone:
        type: 'PCDARTSSearchNetwork'
        C: 16
        num_classes: 1000
        layers: 8
        k: 2
        stem_type: 'imagenet'
    loss:
        type: 'CrossEntropyLoss'

trainer:
    type: 'DARTS'
    stage: ['supernet', 'search']
    #early_stop:
    #    skip_in_norm_cell: 2
    #    arch_rank_stable_epoch: 10
    warmup_epoch: 35
    algorithm:
        type: 'DARTS'
        unrolled: True
        optimizer:
            type: 'Adam'
            lr: 6.e-3
            betas: [0.5, 0.999]
            weight_decay: 1.e-3
