workers: 4
epochs: 120
start_epoch: 0
batch_size: 64
lr_scheduler:
    type: 'cosine'
    lr: 0.2
    warmup_epochs: 0
momentum: 0.9
weight_decay: 4.e-5
nesterov: False
print_freq: 20
resume:
save: './workdir/spos/mbv2-train-search'
evaluate: False
seed: 99

data:
    type: 'imagenet'
    traindir: './data/imagenet_nas/train/'
    trainlabel: './data/imagenet_nas/meta/train.txt'
    valdir: './data/imagenet_nas/train/'
    vallabel: './data/imagenet_nas/meta/val.txt'

model:
    type: 'SPOSModel'
    backbone:
        type: 'mobilenetv2'
    loss:
        type: 'CrossEntropyLabelSmooth'
        num_classes: 1000
        epsilon: 0.1

trainer:
    type: 'SPOS'
    stage: ['supernet', 'search']
    algorithm:
        type: 'SPOS'
        sampler:
            type: 'uniform'
            flops_min: 290000000
            flops_max: 360000000
            max_times: 50
        searcher:    
            type: 'evolution'    
            max_epoch: 20
            flops_limit: 330000000
            population_num: 50
            top_k_num: 10
            mutation_num: 25
            mutation_prob: 0.1
            crossover_num: 25
    evaluator:
        type: 'ImageNet'
        recal_bn_iters: 20
